logging:
  level:
    root: WARN
    org:
      springframework:
        # web: DEBUG
        security: DEBUG

spring:
  # mvc:
  #   log-request-details: true
  #   log-resolved-exception: true
  # codec:
  #   log-request-details: true
  jpa:
    generate-ddl: true
    show-sql: true
  output:
    ansi:
      enabled: always

sentry:
  dsn: https://examplePublicKey@o0.ingest.sentry.io/0
  tracesSampleRate: 1.0

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

server:
  address: 0.0.0.0


  springdoc:
    swagger-ui:
       path: swagger-ui.html

  sentry:
    dsn: https://320ce3d525e2cad38a5c1841686e753a@o4506462269997056.ingest.sentry.io/4506462400348160
    traces-sample-rate: 1.0

